### ISSUE TITLE
Pre-transformation analysis

### ISSUE THREAD

**Issue by LucasBassetti** [OntoUML/ontouml-js#31]
Add parameter to enable pre-transformation analysis to give users feedback about things that could potentially impact the transformation.

Including:
- Name suggestion
- Repeated names (attributes, relation names and association ends, etc.)
- Plural association ends

#### Example

```
preAnalysis: true
```

**Comment by tgoprince** [comment]
What do you mean by `Name suggestion`? Is it to identify elements without name? For instance, an association without name? 

I think we should also check for invalid characters, such as `,` and `.`, which may break the ttl serialization (if there is no way around it)

**Comment by tgoprince** [comment]
Another thing that comes to mind is to check if the chosen prefixes (or package names) clash with  popular prefixes (e.g. `rdfs`, `rdf`, `owl`, `foaf`, `schema`..)
