### ISSUE TITLE
Generate OWL doc for the generated gUFO ontology

### ISSUE THREAD

**Issue by LucasBassetti** [OntoUML/ontouml-js#32]
We need a parameter to generate OWL documentation for the generated ontology

#### Example

```
generateDocumentation: true
```

**Comment by tgoprince** [comment]
I propose we add a HTML documentation in lines with:

- http://open-biomed.sourceforge.net/opmv/ns.html
- http://xmlns.com/foaf/spec/
- http://rdfs.org/sioc/spec/

I don't see a need for us to create our own documentation for now. Maybe we can do that later on by taking advantage of the ontological distinctions in gUFO (e.g. rigidity, dependency, objects vs events).

**Comment by tgoprince** [comment]
This feature became a stand-alone service. Please refer to https://github.com/OntoUML/gufo2html
